### PR TITLE
Job page theming

### PR DESCRIPTION
**Pull request by BenPoole88**
Here’s where I’m up to with the job page theming so far, for you to review. I’ve tweaked the layout so now the jobs are using the 9-3 layout, and I’ve added a few more blocks to it. I have a couple of queries too:

Can I add classes specifically to the Main Content section of the page? I’m currently using .path-job, and nested within that div#main-content. Is there a better way to do this?

Is there any way to contain the Employer Name and Job Title within the same block? In the layout they’re currently in their own individual divs which I’ve styled independently using individual classes.

Thanks!

Job Page Desktop

Job Page Mobile

Job Page Mobile 2

### CODE REVIEW

**Comment by rlmumford** [comment]
I like how the buttons collapse into a bar, I think thats great!

Obviously there's further work still to do here. The swoop for the logo and stuff. I think we do want the grey region touching the header so that needs to be tweaked.

You can make whatever custom blocks you like, maybe we can go through tomorrow?

**Comment by BenPoole88** [comment]
So, I've completely re-done the layout for the job page, using sections and blocks. I've done a 75%-25% 2-column split for the company name/logo, and the job title/apply button (although there's no content in the logo or apply button blocks yet). I've added the primary action buttons below the header section, but I'm having a bit of trouble with the styling, I can't quite work out what I've done to the buttons here, so could do with a bit of help untangling it please!

Screenshot 2020-07-02 at 14 34 55 (2)

**Comment by BenPoole88** [comment]
Is there a pre-existing Logo block to insert, or will it be a case of creating a new custom block?

**Comment by rlmumford** [comment]
> Is there a pre-existing Logo block to insert, or will it be a case of creating a new custom block?

Should just be a case of getting the logo field from the organization? You might have to add organization as context.

**Comment by BenPoole88** [comment]
I've done some styling on the job results page, and the full job page as well. Having a bit of an issue with getting the logos to sit in the upper right corner of their container though, what you can see below is position: absolute, which I know is overlapping one of the logos on top of the other which isn't ideal.

I'm struggling to get to grips with how Drupal and PHP work, it's more complicated than styling for me so I need to understand how Layouts and Views work a bit better, and how I can better use them in relation to css. Is there a beginners resource you can point me in the direction of, maybe like a "Drupal for Dummies" or something?

Screenshot 2020-07-09 at 09 58 14 (2)

Screenshot 2020-07-09 at 10 06 30 (2)

**Comment by rlmumford** [comment]
There's loads of documentation out there. Just google the questions you have and you'll find some answers. I know lullabot is a good resource.

Some of the other issues are more related to the css, so there are other resources on that. Position absolute may be the right was to go in some instances, but you're better making sure its in the right container with the col-X classes. Think about things like "text-align" "float" "vertical-align" or using margins effectively to reposition things.

On the the white region on the search result, I would make it wider, so more of it stretches off the page to the right, or use an :after element to make the swooping white background

**Comment by BenPoole88** [comment]
Job results now have the white extending off the page to the right, logos are now positioned correctly top right (with space for an "Apply Now"/"Bookmark this job" space underneath)

Screenshot 2020-07-13 at 15 17 56 (2)

**Comment by BenPoole88** [comment]
I've pushed where I'm up to with the job pages, I'm still having a bit of an issue with the header, see below. I think I've gotten myself confused between the twig and the view!

Screenshot 2020-07-13 at 15 50 34 (2)

**Pull request merged**
