### PR TITLE
design updates to membership/directory check box section

### PR DESCRIPTION
**Pull request by BenPoole88**
I've made some tweaks to the membership section, I'm not 100% sure if I've got the costs correct but see what you think!

### CODE REVIEW

**Comment by BenPoole88** [comment]
Membership+Directory Selection

**Comment by rlmumford** [comment]
Think I'd get rid of the little blue - after the price. Replace the / with an "or" and make the monthly cost like "£25/month"

**Comment by BenPoole88** [comment]
Just updated this
Membership + Directory Selection

**Comment by rlmumford** [comment]
Hmm, need to make clear that monthly is also plus VAT

**Comment by BenPoole88** [comment]
Good point, thanks Rob! Just did an update
Membership + Directory Selection

**Pull request merged**
